### ISSUE TITLE
429 error

### ISSUE THREAD

**Issue by ghost** [Glarity/reddit2instagrambot#13]
I setup the code it seemed to work fine now when I got to turn on the bot I am getting a 429 error and was wondering what might be the problem here.

Request return 429 error!
{'message': 'Please wait a few minutes before you try again.', 'status': 'fail'}
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Thats the message I get.

**Comment by tylerolson** [comment]
How many times have you logged in recently? Instagram will time out requests if there are too many in a given time period.

**Comment by ghost** [comment]
I dont think I have that many times I mean I left the program to run for a while then it just stopped working or my computer turned off etc when I came back i restarted the program and it kept giving me this error.

**Comment by ghost** [comment]
I reset it up and it is now working I dont know what the issue was but I have fixed it.

**Comment by tylerolson** [comment]
The API is unofficial so Instagram doesn't always act nicely :P
